name: Installer To Exe

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: '3.10'
    - name: PyInstaller Installer Build
      run:
        pip install pyinstaller
        
        pyinstaller Installer/fox_downloader.py --onefile
    - name: Upload Fox Installer Build Artifact
      uses: actions/upload-artifact@v2.3.0
      with:
        name: Fox Installer Binary build
        path: D:\a\fox\fox\dist\fox_downloader.exe
    - name: PyInstaller Fox Build
      run:
        pip install pyinstaller
        
        pyinstaller fox.py --onefile
    - name: Upload Fox Build Artifact
      uses: actions/upload-artifact@v2.3.0
      with:
        name: Fox Binary build
        path: D:\a\fox\fox\dist\fox.exe
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "POTENTIALLY UNSTABLE"
        prerelease: true
        title: "Development Build - Potentially unstable"
        files: |
          dist/fox_downloader.exe
          dist/fox.exe
