name: Fox Installer To Exe

on:
  push:
    branches: [ main ]
    paths:
      - 'fox_downloader.py'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: '3.10'
    - name: PyInstaller Installer Build
      run:
        pip install pyinstaller
        
        pyinstaller mango_downloader.py --onefile
    - name: Upload Fox Installer Build Artifact
      uses: actions/upload-artifact@v2.3.0
      with:
        name: Fox Installer Binary build
        path: D:\a\fox\fox\dist\mango_downloader.exe
