name: Mango To Exe

on:
  push:
    branches: [ main ]
    paths:
      - 'mango.py'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: '3.10'
    - name: PyInstaller Fox Build
      run:
        pip install pyinstaller
    
        pyinstaller mango.py --onefile
    - name: Upload Fox Build Artifact
      uses: actions/upload-artifact@v2.3.0
      with:
        name: Fox Binary build
        path: D:\a\fox\fox\dist\mango.exe
    - name: Upload Fox Source Artifact
      uses: actions/upload-artifact@v2.3.0
      with:
        name: Fox Source File
        path: mango.py

