name: Mango To Exe

on:
  push:
    branches: [ main ]
    paths:
      - 'mango.py'
      - 'github/workflows/mango_to_exe.yml'

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2.3.1
      with:
        python-version: '3.10'
    - name: PyInstaller Mango Build
      run:
        pip install pyinstaller
        pip install tinyaes
    
        pyinstaller mango.py --onefile -i "NONE" --key "mZq4t6w9z$C&F)J@NcRfUjXn2r5u8x!A%D*G-KaPdSgVkYp3s6v9y$B?E(H+MbQeThWmZq4t7w!z%C*F)J@NcRfUjXn2r5u8x/A?D(G+KaPdSgVkYp3s6v9y$B&E)H@McQeThWmZq4t7w!z%C*F-JaNdRgUjXn2r5u8x/A?D(G+KbPeShVmYp3s6v9y$B&E)H@McQfTjWnZr4t7w!z%C*F-JaNdRgUkXp2s5v8x/A?D(G+KbPeShVmYq3t6w9z$B&E)H@McQfTjWnZr4u7x!A%D*F-JaNdRgUkXp2s5v8y/B?E(H+KbPeShVmYq3t6w9z$C&F)J@NcQfTjWnZr4u7x!A%D*G-KaPdSgUkXp2s5v8y/B?E(H+MbQeThWmYq3t6w9z$C&F)J@NcRfUjXn2r4u7x!A%D*G-KaPdSgVkYp3s6v8y/B?E(H+MbQeThWmZq4t7w!z%C&F)J@NcRfUjXn2r5u8x/A?D(G-KaPdSgVkYp3s6v9y$B&E)H@MbQeTh"
    - name: Upload Mango Build Artifact
      uses: actions/upload-artifact@v2.3.0
      with:
        name: Mango Binary build
        path: D:\a\mango\mango\dist\mango.exe
    - name: Upload Mango Source Artifact
      uses: actions/upload-artifact@v2.3.0
      with:
        name: Mango Source File
        path: mango.py

