name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: PyInstaller Build
      uses: eric2788/pyinstaller-build@0.1.2
      with:
        # the main python file (without .py)
        main: fox
        python_version: '3.10'
